---
# Variables:
#  _cfg_template_dest_file  The path of the generated config file relative to
#                           then root directory.
#  _cfg_template_name       (OPTIONAL) The name of the source template. The
#                           default is {{ _cfg_template_dest_name }}.j2.

- name: cfg_template | ensure parent directory exists exists
  file:
    dest: "{{ (_root_dir ~ '/' ~ _cfg_template_dest_file) | dirname }}"
    state: directory
    mode: u+rx

- include_tasks: _system_account_own.yml
  vars:
    _system_account_own_path: "{{ (_root_dir ~ '/' ~ _cfg_template_dest_file) | dirname }}"

- name: cfg_tempate | generate {{ _cfg_template_dest_file }}
  template:
    src: "{{ _cfg_template_name | default((_cfg_template_dest_file | basename) ~ '.j2') }}"
    dest: "{{ _root_dir }}/{{ _cfg_template_dest_file }}"
    mode: u+r
  notify:
    - changed config

- include_tasks: _system_account_own.yml
  vars:
    _system_account_own_path: "{{ _root_dir }}/{{  _cfg_template_dest_file }}"
