---
- name: Hosts config | validate address type
  when: _validate | bool
  with_items: "{{ _host_entries }}"
  ansible.builtin.assert:
    that: item.address_type == 'local' or item.address_type == 'remote'
  failed_when: false

- name: Hosts config | generate file
  ansible.builtin.include_tasks: _cfg_template.yml
  vars:
    _cfg_template_dest_file: etc/irods/hosts_config.json

- name: Hosts config | ensure known that changes were made
  ansible.builtin.meta: flush_handlers
