---
- name: irods_environment | load variable values
  ansible.builtin.include_vars: >-
    {{ 'irods_environment_server.yml' if _for_server|bool else 'irods_environment_client.yml' }}

- when: _validate | bool
  ignore_errors: true
  block:
    - name: irods_environment | validate core variables
      ansible.builtin.assert:
        that:
          - _zone_port|int >= 1 and _zone_port|int <= 65535

    - name: irods_environment | validate variables
      when: _for_server | bool
      ansible.builtin.assert:
        that:
          - _client_server_negotiation in ['off', 'request_server_negotiation']
          - _client_server_policy in ['CS_NEG_DONT_CARE', 'CS_NEG_REFUSE', 'CS_NEG_REQUIRE']
          - _client_default_hash_scheme in ['MD5', 'SHA256']
          - _client_encryption_key_size|int >= 0
          - _client_encryption_num_hash_rounds|int >= 0
          - _client_encryption_salt_size|int >= 0
          - _cwd is match('^/..*')
          - _home is match('/..*')
          - not _log_level or (_log_level|int >= 1 and _log_level|int <= 10)
          - _match_hash_policy in ['compatible', 'strict']
          - not _server_control_plane_key or _server_control_plane_key | length == 32
          - >
            not _server_control_plane_port
            or (
              _server_control_plane_port|int >= 1 and _server_control_plane_port|int <= 65535
              and _server_control_plane_port|int != _zone_port|int )
          - not _ssl_verify_server or _ssl_verify_server in ['cert', 'hostname', 'none']
          - >
            not _client_xmsg_port
            or (
              _client_xmsg_port|int >= 1 and _client_xmsg_port|int <= 65535
              and _client_xmsg_port|int != _zone_port|int
              and _client_xmsg_port|int != _server_control_plane_port|int )
          - not _zone_auth_scheme or _zone_auth_scheme in ['gsi', 'krb', 'native', 'pam']

- name: irods_environment | generate file
  ansible.builtin.include_tasks: _cfg_template.yml
  vars:
    _cfg_template_dest_file: "{{ _environment_file }}"
    _cfg_template_name: irods_environment.json.j2

- name: irods_environment | ensure known that changes were made
  ansible.builtin.meta: flush_handlers
