---
- when: _icat is mapping
  block:
    - name: odbc | load vars for chosen database type
      ansible.builtin.include_vars: "{{ _icat.catalog_database_type }}.yml"

    - name: odbc | create .odbc.ini
      ansible.builtin.include_role:
        name: cyverse.unixodbc_cfg
        tasks_from: odbc.yml
      vars:
        base_driver_properties:
          Description: iRODS Catalog
          Servername: "{{ _icat.db_host }}"
          Port: "{{ _icat.db_port }}"
          Database: "{{ _icat.db_name }}"
        unixodbc_cfg_odbcini_path: "{{ _root_dir }}/var/lib/irods"
        unixodbc_cfg_user: "{{ _system_account_name if _chown else None }}"
        unixodbc_cfg_group: "{{ _system_group_name if _chown else None }}"
        unixodbc_cfg_sources:
          - source_name: iRODS Catalog
            driver_file: >-
              {{ _icat.odbc_driver if _icat.odbc_driver|default(none) else
                _dbms_default_odbc_driver }}
            driver_properties: >-
              {{ base_driver_properties | combine(_dbms_specific_odbc_properties) }}
