---
- name: Server config | include variables
  ansible.builtin.include_vars: server_config.yml

- name: Server config | validate ICAT vars if requested
  when: _validate | bool and _database is mapping
  ansible.builtin.assert:
    that:
      - _database.catalog_database_type in ('mysql', 'oracle', 'postgres')
      - _database.db_port|int >= 1 and _database.db_port|int <= 65535

- name: Server config | validate rest if requested
  when: _validate | bool
  block:
    - name: Validate federation
      loop: "{{ _federation }}"
      ansible.builtin.assert:
        that:
          - item.zone_name != _zone_name
          - item.negotiation_key|length == 32

    - name: Validate parameters
      ansible.builtin.assert:
        that:
          - _catalog_provider_hosts|length >= 1
          - _catalog_service_role in ['consumer', 'provider']
          - _default_number_of_transfer_threads|int > 0
          - _default_temporary_password_lifetime|int > 0
          - _maximum_temporary_password_lifetime|int >= _default_temporary_password_lifetime|int
          - _maximum_size_for_single_buffer|int >= 0
          - _transfer_buffer_size_for_parallel_transfer|int > 0
          - _transfer_chunk_size_for_parallel_transfer|int > 0
          - _default_hash_scheme in ['MD5', 'SHA256']
          - _match_hash_policy in ['compatible', 'strict']
          - _negotiation_key|length == 32
          - _server_control_plane_encryption_num_hash_rounds|int >= 0
          - not _server_control_plane_key or _server_control_plane_key|length == 32
          - >
            not _server_control_plane_port
            or (_server_control_plane_port|int >= 1 and _server_control_plane_port|int <= 65535)
          - _server_control_plane_timeout|int > 0
          - _server_port_range_end|int >= 1 and _server_port_range_end|int <= 65535
          - >
            _server_port_range_start|int >= 1
            and _server_port_range_start|int <= _server_port_range_end|int
          - >
            _server_control_plane_port|int < _server_port_range_start|int
            or _server_control_plane_port|int > _server_port_range_end|int
          - _zone_auth_scheme in ['native', 'pam_password']
          - not _zone_key is match('.*-.*')
          - >
            _zone_port|int >= 1 and _zone_port|int <= 65535
            and _zone_port != _server_control_plane_port
            and (
              _zone_port|int < _server_port_range_start|int
              or _zone_port|int > _server_port_range_end|int)

- name: Server config | generate file
  ansible.builtin.include_tasks: _cfg_template.yml
  vars:
    _cfg_template_dest_file: etc/irods/server_config.json

- name: Server config | ensure known that changes were made
  ansible.builtin.meta: flush_handlers
