---
- name: version | get current time
  when: ansible_date_time is not defined
  ansible.builtin.setup:
    filter:
      - ansible_date_time
  delegate_to: localhost
  run_once: true

- name: version | retrieve VERSION.json.dist
  slurp:
    path: "{{ _root_dir }}/var/lib/irods/VERSION.json.dist"
  register: slurp_resp

- name: version | extract dist version
  ansible.builtin.set_fact:
    dist_ver: "{{ slurp_resp.content | b64decode }}"

- name: version | check if VERSION.json exists
  ansible.builtin.stat:
    path: "{{ _root_dir }}/var/lib/irods/VERSION.json"
  register: stat_resp

- name: version | create VERSION.json
  when: not stat_resp.stat.exists
  ansible.builtin.copy:
    dest: "{{ _root_dir }}/var/lib/irods/VERSION.json"
    content: "{{ 
      dist_ver 
        | combine({ 'installation_time': ansible_date_time.iso8601_micro }) 
        | to_nice_json(indent=4) }}"
    force: no
    mode: u+r

- when: stat_resp.stat.exists
  block:
    - name: version | retrieve VERSION.json
      ansible.builtin.slurp:
        path: "{{ _root_dir }}/var/lib/irods/VERSION.json"
      register: slurp_resp

    - name: version | extract version
      ansible.builtin.set_fact:
        ver: "{{ slurp_resp.content | b64decode }}"

    - name: version | update VERSION.json
      when: dist_ver['irods_version'] is version(ver['irods_version'], '>')
      ansible.builtin.copy:
        dest: "{{ _root_dir }}/var/lib/irods/VERSION.json"
        content: "{{ 
          dist_ver
            | combine(
              { 'installation_time': ansible_date_time.iso8601_micro, 'previous_version': ver } ) 
            | to_nice_json(indent=4) }}"
        mode: u+r

- name: version | ensure system account owns file
  ansible.builtin.include_tasks: _system_account_own.yml
  vars:
    _system_account_own_path: "{{ _root_dir }}/var/lib/irods/VERSION.json"