---
- name: Converge | client deposition
  hosts: all
  gather_facts: false
  tasks:
    - name: Place default client env file
      ansible.builtin.import_role:
        name: ansible-irods-cfg
        tasks_from: client.yml
      tags: skip_ansible_lint

    - name: Place custom client env file
      ansible.builtin.include_role:
        name: ansible-irods-cfg
        tasks_from: client.yml
      vars:
        irods_cfg_chown: false
        irods_cfg_environment_file: tmp/ie.json
