---
- name: converge | client deposition
  hosts: all
  gather_facts: false
  tasks:
    - name: place default client env file
      import_role:
        name: ansible-irods-cfg
        tasks_from: client.yml

    - name: place custom client env file
      include_role:
        name: ansible-irods-cfg
        tasks_from: client.yml
      vars:
        irods_cfg_chown: false
        irods_cfg_environment_file: tmp/ie.json
