---
- name: Base | prepare
  ansible.builtin.import_playbook: ../_shared/prepare.yml


- name: Prepare
  hosts: all
  tasks:
    - name: Create irods service account
      ansible.builtin.user:
        name: irods
        home: /var/lib/irods

    - name: Create configuration schemas directory
      ansible.builtin.file:
        path: /var/lib/irods/configuration_schemas/v4
        state: directory
        recurse: true
        mode: u+rx

    - name: Download configuration schemas
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/irods/irods/refs/heads/main/schemas/configuration/v4/{{ item }}.in
        dest: /var/lib/irods/configuration_schemas/v4/{{ item }}
        mode: u+r
        timeout: 120
      register: download
      until: download is not failed
      retries: 10
      loop:
        - client_environment.json
        - database_config.json
        - host_access_control.json
        - host_resolution.json
        - rule_engine.json
        - server_config.json
        - service_account_environment.json

    - name: Expand server_config schema template values
      ansible.builtin.lineinfile:
        path: /var/lib/irods/configuration_schemas/v4/{{ item }}
        regexp: '^(.*)@IRODS_CONFIGURATION_SCHEMA_PREFIX@@IRODS_HOME_DIRECTORY@(.*)$'
        line: '\1var/lib/irods\2'
        backrefs: true
      loop:
        - client_environment.json
        - database_config.json
        - host_access_control.json
        - host_resolution.json
        - rule_engine.json
        - server_config.json
        - service_account_environment.json
