---
- name: Converge
  hosts: all
  collections:
    - ansible.builtin
  tasks:
    - name: Do not give file irods ownership
      ansible.builtin.include_role:
        name: ansible-irods-cfg
        tasks_from: _system_account_own.yml
      vars:
        irods_cfg_chown: false
        irods_cfg_validate: true
        _system_account_own_path: /etc/irods/not_owner_test

    - name: Give file irods ownershop
      ansible.builtin.include_role:
        name: ansible-irods-cfg
        tasks_from: _system_account_own.yml
      vars:
        irods_cfg_chown: true
        irods_cfg_validate: true
        _system_account_own_path: /etc/irods/owner_test