# Input Parameters:
#   cfg_path: The absolute path to the configuration file to be validated
#   schema_path: The absolute path to the schema file used for validation
---
- name: check {{ cfg_path }} deposition
  ansible.builtin.stat:
    path: "{{ cfg_path }}"
  register: response
  failed_when: >-
    not response.stat.exists
    or response.stat.pw_name != 'irods'
    or response.stat.gr_name != 'irods'

- name: validate {{ cfg_path }} with schema
  ansible.builtin.command: >
    jsonschema --instance '{{ cfg_path }}' '{{ schema_path }}'
  register: response
  until: response.stderr is not search('Connection timed out')
  retries: 10
  changed_when: false