---
- name: converge | provider
  hosts: all
  roles:
    - role: ansible-irods-cfg  # XXX: ansible-lint<6 generates internal error here in vscode

  post_tasks:
    - name: place setup_configuration.json
      import_role:
        name: ansible-irods-cfg
        tasks_from: setup_irods.yml