---
- name: Converge | provider
  hosts: all
  tasks:
    - name: Place setup_configuration.json
      ansible.builtin.import_role:
        name: ansible-irods-cfg
        tasks_from: setup_irods.yml
      tags: skip_ansible_lint
