---
- import_playbook: ../_shared/prepare.yml


- name: Prepare | provider
  hosts: centos
  become: true
  collections:
    - community.general
  tasks:
    - name: CentOS | install yum_versionlock requirements
      ansible.builtin.package:
        name:
          - yum
          - yum-versionlock
        state: present

    - name: CentOS | install iRODS package repository signing key
      ansible.builtin.rpm_key:
        key: https://packages.irods.org/irods-signing-key.asc

    - name: CentOS | install iRODS repository
      ansible.builtin.get_url:
        url: https://packages.irods.org/renci-irods.yum.repo
        dest: /etc/yum.repos.d/renci-irods.yum.repo
        mode: u+r

    - name: CentOS | force import of GPG key
      ansible.builtin.shell: |
        if ! resp="$(yum --assumeyes updateinfo)"; then
          exit 1
        fi
        if [[ "$resp" =~ irods-signing-key ]]; then
          echo changed
        fi
      register: response
      changed_when: response.stdout == 'changed'

    - name: CentOS | lock irods packages to required version
      yum_versionlock:
        name:
          - irods-icommands-4.2.8
          - irods-database-plugin-postgres-4.2.8
          - irods-runtime-4.2.8
          - irods-server-4.2.8
        state: present

    - name: CentOS | install OS specific required packages
      ansible.builtin.package:
        name: which
        state: present

      # TODO: When upgrading to iRODS 4.2.9+, remove this task.
    - name: CentOS | ensure unixODBC is installed (irods issue 5389)
      ansible.builtin.package:
        name: unixODBC
        state: present

    - name: CentOS | install PostgreSQL server
      ansible.builtin.package:
        name:
          - postgresql-contrib
          - postgresql-odbc
          - postgresql-server
        state: present

    - name: CentOS | install prerequisites for psycopg2
      ansible.builtin.yum:
        name: 
          - "@Development tools"
          - postgresql-devel
        state: present


- name: Prepare | provider
  hosts: centos
  become: true
  become_user: postgres
  become_flags: '-i'
  gather_facts: false
  tasks:
    - name: CentOS | initialize PostgreSQL database cluster
      ansible.builtin.shell: |
        if [[ -e "$PGDATA" ]] && [[ -z "$(ls --almost-all "$PGDATA")" ]]; then
          initdb --pgdata="$PGDATA" --auth=ident
        fi
      register: response
      changed_when: response.stdout != ''

    - name: CentOS | create PostgreSQL log directory
      ansible.builtin.file:
        path: /var/lib/pgsql/data/pg_log
        state: directory
        mode: u+r

    - name: CentOS | start PostgreSQL
      ansible.builtin.shell: |
        set -o errexit
        if ! [[ -e "$PGDATA"/postmaster.pid ]]; then
          pg_ctl start > /dev/null
          echo changed
        fi
      register: response
      changed_when: response.stdout == 'changed'


- name: prepare | provider
  hosts: ubuntu
  tasks:
    - name: Ubuntu | install apt_key prerequisites
      ansible.builtin.package:
        name: gpg
        state: present

    - name: Ubuntu | install iRODS package repository signing key
      ansible.builtin.apt_key:
        url: https://packages.irods.org/irods-signing-key.asc

    - name: Ubuntu | install iRODS repository
      ansible.builtin.copy:
        dest: /etc/apt/sources.list.d/renci-irods.list
        mode: u+rw
        content: |
          deb [arch=amd64] https://packages.irods.org/apt/ {{ ansible_lsb.codename }} main

    - name: Ubuntu | lock iRODS packages to required version
      ansible.builtin.copy:
        dest: /etc/apt/preferences.d/irods
        mode: u+rw
        content: |
          Package: irods-*
          Pin: version 4.2.8
          Pin-Priority: 1001

    - name: Ubuntu | update apt cache
      ansible.builtin.apt:
        update_cache: true

    - name: Ubuntu | install PostgreSQL server
      ansible.builtin.package:
        name: postgresql
        state: present

    - name: Ubuntu | start PostgreSQL 
      ansible.builtin.service:
        name: postgresql
        state: started
        enabled: true

    - name: Ubuntu | install prerequisites for psycopg2
      ansible.builtin.package:
        name: libpq-dev
        state: present


- name: prepare | provider
  hosts: all
  gather_facts: false
  tasks:
    - name: Install prerequisites for psycopg2
      ansible.builtin.pip:
        name: wheel

    - name: Install postgresql module prerequisites
      ansible.builtin.pip:
        name: psycopg2

    - name: Install iRODS server
      ansible.builtin.package:
        name: 
          - irods-database-plugin-postgres
          - irods-server
        state: present


- name: Prepare | provider
  hosts: all
  become: true
  become_user: postgres
  become_flags: '-i'
  gather_facts: false
  collections:
    - community.postgresql
  tasks:
    - name: Create ICAT DB
      postgresql_db:
        name: ICAT

    - name: Create iRODS user
      postgresql_user:
        db: ICAT
        name: irods
        password: testpassword
        priv: ALL

    - name: Ensure postgres_pg_hba prerequisites are installed
      ansible.builtin.pip:
        name: ipaddress

    - name: Configure irods user ICAT access
      postgresql_pg_hba:
        dest: "{{ pg_hba_path }}"
        contype: host
        users: irods
        source: 127.0.0.1/32
        databases: ICAT
        method: md5
        state: present
      notify: Reload postgres, {{ inventory_hostname }}

  handlers:
    - name: Reload postgres, centos
      command: pg_ctl reload

    - name: Reload postgres, ubuntu
      service:
        name: postgresql
        state: reloaded