---
- import_playbook: ../_shared/prepare.yml


- name: prepare 
  hosts: all
  collections:
    - ansible.builtin
  tasks:
    - name: download configuration schemas
      get_url:
        url: https://schemas.irods.org/configuration/v3/{{ item }}
        dest: /var/lib/irods/
        timeout: 120
      register: download
      until: download is not failed
      retries: 10
      with_items:
        - host_access_control_config.json
        - hosts_config.json
        - server_config.json
        - service_account_environment.json

    - name: create VERSION.json
      copy:
        dest: /var/lib/irods/VERSION.json
        content: |
          {
              "build_system_information": "Linux default-cloud-hostname 3.10.0-229.1.2.el7.x86_64 #1 SMP Fri Mar 27 03:04:26 UTC 2015 x86_64 x86_64", 
              "catalog_schema_version": 4, 
              "commit_id": "bb48cd38c4a543ad8bf45082fa06b15290378b50", 
              "compile_time": "2016-11-04T17:21:01Z", 
              "compiler_version": "g++ (GCC) 4.8.3 20140911 (Red Hat 4.8.3-9)", 
              "configuration_schema_version": 2, 
              "installation_time": "2019-05-06T20:27:21Z", 
              "irods_version": "4.1.10"
          }
        owner: irods
        group: irods
        mode: u+r

    - name: create VERSION.json.dist
      copy:
        dest: /var/lib/irods/VERSION.json.dist
        content: |
          {
              "irods_version": "4.2.8",
              "catalog_schema_version": 7,
              "commit_id": "9eb6c23df45cdedff8ee9c3af71a65d304635037",
              "configuration_schema_version": 3
          }
        owner: irods
        group: irods
        mode: u+r
