---
- import_playbook: ../_shared/prepare.yml


- name: prepare | provider | centos
  hosts: centos
  collections:
    - ansible.builtin
    - community.general
  tasks:
    - name: install yum_versionlock requirements
      package:
        name:
          - yum
          - yum-versionlock
        state: present

    - name: install iRODS package repository signing key
      rpm_key:
        key: https://packages.irods.org/irods-signing-key.asc

    - name:  install iRODS repository
      get_url:
        url: https://packages.irods.org/renci-irods.yum.repo
        dest: /etc/yum.repos.d/renci-irods.yum.repo

    - name: force import of GPG key
      shell: |
        if ! resp="$(yum --assumeyes updateinfo)"; then
          exit 1
        fi
        if [[ "$resp" =~ irods-signing-key ]]; then
          echo changed
        fi
      register: response
      changed_when: response.stdout == 'changed'

    - name: lock irods packages to required version
      yum_versionlock:
        name:
          - irods-icommands-4.2.8
          - irods-database-plugin-postgres-4.2.8
          - irods-runtime-4.2.8
          - irods-server-4.2.8
        state: present

    - name: install OS specific required packages
      package:
        name: which
        state: present

      # TODO: When upgrading to iRODS 4.2.9, remove this task.
    - name: ensure unixODBC is installed (irods issue 5389)
      package:
        name: unixODBC
        state: present

    - name: install PostgreSQL server
      package:
        name:
 #         - postgresql-odbc
          - postgresql-server
        state: present

    - name: initialize PostgreSQL database cluster
      shell: |
        if [[ -e /var/lib/pgsql/data ]] && [[ -z "$(ls --almost-all /var/lib/pgsql/data)" ]]; then
          postgresql-setup initdb
        fi
      register: response
      changed_when: response.stdout is match('Initializing database ')


- name: prepare | provider | ubuntu
  hosts: ubuntu
  collections:
    - ansible.builtin
  tasks:
    - name: install apt_key prerequisites
      package:
        name: gpg
        state: present

    - name: install iRODS package repository signing key
      apt_key:
        url: https://packages.irods.org/irods-signing-key.asc

    - name: install iRODS repository
      copy:
        dest: /etc/apt/sources.list.d/renci-irods.list
        mode: u+rw
        content: |
          deb [arch=amd64] https://packages.irods.org/apt/ {{ ansible_lsb.codename }} main

    - name: lock iRODS packages to required version
      copy:
        dest: /etc/apt/preferences.d/irods
        mode: u+rw
        content: |
          Package: irods-*
          Pin: version 4.2.8
          Pin-Priority: 1001

    - name: update apt cache
      apt:
        update_cache: true

    - name: install PostgreSQL server
      package:
        name: postgresql
        state: present


- name: prepare | provider
  hosts: all
  collections:
    - ansible.builtin
  gather_facts: false
  tasks:
    - name: install iRODS server
      package:
        name: 
          - irods-database-plugin-postgres
          - irods-server
        state: present

    - name: start PostgreSQL 
      service:
        name: postgresql
        state: started
        enabled: true

TODO Deal with bullshit related to ansible and Python 2

    - name: install pip module prerequisites
      package:
        name: python-pip
        state: present

    - name: install postgresql module prerequisites
      pip:
        name: psycopg2


- name: prepare | provider | ICAT DB
  hosts: all
  become: true
  become_user: postgres
  gather_facts: false
  collections:
    - community.postgresql
  tasks:
    - name: create ICAT DB
      postgresql_db:
        name: ICAT

    - name: create iRODS user
      postgresql_user:
        db: ICAT
        name: irods
        password: testpassword
        privs: ALL
