---
- import_playbook: ../_shared/prepare.yml


- name: prepare
  hosts: all
  collections:
    - ansible.builtin
  tasks:
    - name: download configuration schemas
      get_url:
        url: https://schemas.irods.org/configuration/v3/{{ item }}
        dest: /var/lib/irods/
        timeout: 120
      register: download
      until: download is not failed
      retries: 10
      with_items:
        - host_access_control_config.json
        - hosts_config.json
        - server_config.json
        - service_account_environment.json
