---
- name: verify
  hosts: all
  collections:
    - ansible.builtin
  tasks:
    - include_tasks: ../_shared/tasks/validate_deposition.yml
      vars:
        cfg_path: /etc/irods/{{ item }}
        schema: "{{ item }}"
      with_items:
        - host_access_control_config.json
        - hosts_config.json
        - server_config.json

    - name: verify that database_config.json was not deposited
      stat:
        path: /etc/irods/database_config.json
      register: response
      failed_when: response.stat.exists

    - include_tasks: ../_shared/tasks/validate_deposition.yml
      vars:
        cfg_path: /var/lib/irods/.irods/irods_environment.json
        schema: service_account_environment.json

    - name: check service_account.config deposition
      stat:
        path: /etc/irods/service_account.config
      register: response
      failed_when: >-
        not response.stat.exists or
        response.stat.pw_name != 'irods' or
        response.stat.gr_name != 'irods'
