---
dependency:
  name: galaxy
  options:
    requirements-file: molecule/_shared/requirements.yml
driver:
  name: docker
platforms:
  - name: centos
    image: centos:7
    hostname: centos.localdomain
  - name: ubuntu
    image: ubuntu:bionic
    hostname: ubuntu.localdomain
provisioner:
  name: ansible
  inventory:
    group_vars:
      all:
        irods_cfg_validate: true
    host_vars:
      centos:
        pg_hba_path: /var/lib/pgsql/data/pg_hba.conf
      ubuntu:
        pg_hba_path: /etc/postgresql/10/main/pg_hba.conf
        irods_config_icat:
          odbc_driver: PostgreSQL Unicode
verifier:
  name: ansible