---
dependency:
  name: galaxy
  options:
    requirements-file: molecule/_shared/requirements.yml
driver:
  name: docker
platforms:
  - name: centos
    image: centos/systemd:latest
    command: /usr/sbin/init
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    hostname: centos.localdomain
  - name: ubuntu
    image: ubuntu:bionic
    hostname: ubuntu.localdomain
provisioner:
  name: ansible
  inventory:
    group_vars:
      all:
        irods_cfg_validate: true
verifier:
  name: ansible