---
- name: prepare | control node
  hosts: localhost
  tasks:
    - name: install Jinja 3
      pip:
        name: Jinja2>3


- name: Prepare | base 
  hosts: centos
  tasks:
    - name: CentOS | install epel repo
      package:
        name: epel-release
        state: present
 
    - name: CentOS | install pip module prerequisites
      ansible.builtin.package:
        name: python-pip
        state: present

    - name: CentOS | get pip version
      ansible.builtin.shell: |
        set -o pipefail
        pip --version | cut --delimiter=' ' --fields=2
      register: ver_response
      changed_when: false

    - name: CentOS | update pip to 9
      when: ver_response.stdout is version_compare('9.0.3', '<')
      ansible.builtin.pip:
        name: 'pip==9.0.3'
        extra_args: '--upgrade'

    - name: CentOS | update pip to 20
      when: ver_response.stdout is version_compare('20.3.4', '<')
      ansible.builtin.pip:
        name: 'pip==20.3.4'
        extra_args: '--upgrade'


- name: Prepare | base
  hosts: ubuntu
  tasks:
    - name: Ubuntu | initialize apt cache
      apt:
        update_cache: true

    - name: Ubuntu | install pip module prerequisites
      ansible.builtin.package:
        name: python3-pip


- name: prepare | base
  hosts: all
  gather_facts: false
  tasks:
    - name: update ca-certificates
      package:
        name: ca-certificates
        state: latest  # noqa package-latest
        
    - name: install setuptools
      ansible.builtin.pip:
        name: setuptools

    - name: install jsonschema
      ansible.builtin.pip:
        name: jsonschema
        
    - name: create irods user
      user:
        name: irods
        home: /var/lib/irods