---
name: Test
on: [ push, pull_request, workflow_dispatch ]
jobs:
  molecule:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          path: "${{ github.repository }}"

      - uses: robertdebock/molecule-action@5.0.3
        with:
          command: --base-config molecule/_shared/base.yml test --all
