---
name: Test
on: [ push, pull_request, workflow_dispatch ]
jobs:
  molecule:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with: 
          path: "${{ github.repository }}"
 
      - uses: gofrolist/molecule-action
        with:
          molecule_options: --base-config molecule/_shared/base.yml
          molecule_command: test
          molecule_args: --all
