---
name: Test
on: [ push, pull_request, workflow_dispatch ]
jobs:
  molecule:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with: 
          path: "${{ github.repository }}"
 
      - uses: gofrolist/molecule-action@v2.2.44
        with:
          molecule_options: --base-config molecule/_shared/base.yml
          molecule_command: test
          molecule_args: --all
